version: 2.1

executors:
  python3-executor:
    docker:
      - image: circleci/python:3.6

jobs:

  syntax-checks:
    executor: python3-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install flake8

      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 --exclude venv --max-line-length=100 --extend-ignore=E203 --show-source

      - run:
          name: Check critical errors
          command: |
            . venv/bin/activate
            flake8 --exclude venv --count --select=E901,E999,F821,F822,F823 --show-source --statistics

  code-coverage:
    executor: python3-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install coverage pytest pytest-html
      - run:
          name: Unittest
          command: |
            . venv/bin/activate
            pytest --html=report.html
            coverage run -m pytest -v
      - store_artifacts:
          path: report.html

      - run:
          name: Code coverage
          command: |
            . venv/bin/activate
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  code-quality:
    jobs:
      - syntax-checks
      - code-coverage:
          requires:
            - syntax-checks

